version: "3.5"
services:
  payever:
    build: .
    container_name: payever
    restart: always
    depends_on:
      - mongodb
      - rabbitmq
      - redis
    ports:
      - "3000:3000"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # number of files or file count
        max-size: "2000m" # file size

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: payever
      RABBITMQ_DEFAULT_PASS_FILE: /run/secrets/rabbitmq_password
    secrets:
      - rabbitmq_password
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    command: "redis-server"
    networks:
      - backend
    logging:
      driver: "json-file"
      options:
        max-file: "5" # number of files or file count
        max-size: "2000m" # file size


  mongodb:
    build: ./mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: admin
      MONGO_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_DATABASE: payever
    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_password
      - mongodb_username
    networks:
      - backend

secrets:
  mongodb_root_password:
    file: ./mongodb/secrets/.mongodb_root_password
  mongodb_root_username:
    file: ./mongodb/secrets/.mongodb_root_username
  mongodb_password:
    file: ./mongodb/secrets/.mongodb_password
  mongodb_username:
    file: ./mongodb/secrets/.mongodb_username
  rabbitmq_password:
    file: ./rabbitmq/secrets/.rabbitmq_password
networks:
  backend: